train:
 lr: 3e-4
 momentum: 0.9
 weight_decay: 1e-6
 epochs: 100
 eval_every_n_epochs: 1
 fine_tune_from: "May14_11-52-39_yq01-qianmo-com-127-2-15.yq01.baidu.com"
 log_every_n_steps: 50
 fp16_precision: False
 train_batch_size_per_gpu: 128
 warmup_epochs: 1

model:
  out_dim: 128
  base_model: "resnet50"

gpu:
  gpu_ids: "4,5,6,7"
  gpunum: 4
  
dataset:
  data_root: './data' 
  dataset_name: 'select_base_200e'
  s: 1
  input_shape: (224,224,3)
  num_workers: 64
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
